fix of issue no #71
kucc1997/kucc-website pull request #74
Opened 2024-04-21 15:14 UTC by razzat008

- Added routes for non-existing pages/urls 
- Added png for the error code-404

2024-04-25 13:34 UTC, abhiyandhakal commented
@razzat008 thank you for your PR. Please include the issue number in the body of the pull request (also). For now, I've edited it, if you don't mind.

2024-04-25 13:36 UTC, abhiyandhakal commented on src/pages/PageNotFound.jsx
> +        <p className="text-lg text-gray-600">The page you're looking for doesn't exist.</p>
Also add the link to the homepage

2024-04-25 13:38 UTC, abhiyandhakal requested changes
Please make the necessary changes

2024-04-25 14:08 UTC, razzat008 commented on src/pages/PageNotFound.jsx
> +        <p className="text-lg text-gray-600">The page you're looking for doesn't exist.</p>
I will make the changes
Thanks

2024-04-28 13:33 UTC, abhiyandhakal approved these changes

2024-04-28 13:33 UTC, merged